# Generated by Django 2.2.5 on 2021-07-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('city', models.CharField(choices=[('제주시', '제주시'), ('조천읍', '조천읍'), ('구좌읍', '구좌읍'), ('우도', '우도'), ('성산읍', '성산읍'), ('포선면', '포선면'), ('남원읍', '남원읍'), ('서귀포시', '서귀포시'), ('중문', '중문'), ('안덕면', '안덕면'), ('대정읍', '대정읍'), ('한경읍', '한경면'), ('한림읍', '한림읍'), ('애월읍', '애월읍')], max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
            ],
            options={
                'verbose_name': 'Guest House',
            },
        ),
        migrations.CreateModel(
            name='SignatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('signature_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signature_photo')),
                ('price', models.IntegerField(default=0)),
                ('start_at', models.TimeField(null=True)),
                ('signature_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Signature', to='guesthouses.SignatureType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='guesthouse_photos')),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='guesthouses.GuestHouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
