# Generated by Django 2.2.5 on 2021-07-07 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guesthouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesthouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='signature',
            field=models.ManyToManyField(blank=True, related_name='GuestHouse', to='guesthouses.Signature'),
        ),
    ]
