# Generated by Django 2.2.5 on 2021-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouses', '0002_auto_20210707_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesthouse',
            name='city',
            field=models.CharField(choices=[('제주', '제주시'), ('조천', '조천읍'), ('구좌', '구좌읍'), ('우도', '우도'), ('성산', '성산읍'), ('포선', '포선면'), ('남원', '남원읍'), ('서귀포', '서귀포시'), ('중문', '중문'), ('안덕', '안덕면'), ('대정', '대정읍'), ('한경', '한경면'), ('한림', '한림읍'), ('애월', '애월읍')], max_length=80),
        ),
    ]
