# Generated by Django 2.2.5 on 2021-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouses', '0002_auto_20210707_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='signature_type',
            field=models.ManyToManyField(blank=True, related_name='GuestHouse', to='guesthouses.SignatureType'),
        ),
    ]
