# Generated by Django 2.2.5 on 2021-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouses', '0003_auto_20210707_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesthouse',
            name='city',
            field=models.CharField(choices=[('제주시', '제주시'), ('조천읍', '조천읍'), ('구좌읍', '구좌읍'), ('우도', '우도'), ('성산읍', '성산읍'), ('포선면', '포선면'), ('남원읍', '남원읍'), ('서귀포시', '서귀포시'), ('중문', '중문'), ('안덕면', '안덕면'), ('대정읍', '대정읍'), ('한경읍', '한경면'), ('한림읍', '한림읍'), ('애월읍', '애월읍')], max_length=80),
        ),
    ]
