# Generated by Django 2.2.5 on 2021-07-07 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guesthouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Advantage_review', models.TextField(null=True)),
                ('Weakness_review', models.TextField(null=True)),
                ('rating', models.IntegerField(default=5)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guesthouses.GuestHouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
